export type Product = {
  id: string;
  name: string;
  category: "Insecticides" | "Herbicides" | "Fungicides" | "PGR" | "Bio-Fertilizers" | "Fertilizers";
  composition: string;
  dose: string;
  packingSizes: string[];
  suitableCrops: string[];
  description?: string;
};

export const products: Product[] = [
  // Insecticides (17 products)
  {
    id: "larimon",
    name: "Larimon",
    category: "Insecticides",
    composition: "Lambda-Cyhalothrin 4.9% CS",
    dose: "100-300 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L", "5 L"],
    suitableCrops: ["Cotton", "Rice", "Tomato", "Brinjal", "Chili", "Grapes"],
  },
  {
    id: "kilkari",
    name: "Kilkari",
    category: "Insecticides",
    composition: "Thiamethoxam 12.6% + Lambda-cyhalothrin 9.5% ZC",
    dose: "80 ml/200L",
    packingSizes: ["50 ml", "100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Fruits", "Vegetables", "Cereals", "Ornamentals"],
  },
  {
    id: "novamet",
    name: "Novamet",
    category: "Insecticides",
    composition: "Novaluron 5.25% + Emamectin Benzoate 0.9% SC",
    dose: "350-400 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Tobacco", "Cabbage", "Cauliflower", "Brinjal", "Tomato", "Okra"],
  },
  {
    id: "compound-505",
    name: "Compound 505",
    category: "Insecticides",
    composition: "Chlorpyriphos 50% + Cypermethrin 5% EC",
    dose: "250-400 ml/acre",
    packingSizes: ["250 ml", "500 ml", "1 L", "5 L"],
    suitableCrops: ["Cotton", "Paddy", "Chili", "Tomato", "Brinjal", "Soybean", "Groundnut", "Vegetables"],
  },
  {
    id: "brofen",
    name: "Brofen",
    category: "Insecticides",
    composition: "Buprofezin 25% SC",
    dose: "400 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Rice", "Cotton", "Chili", "Mango", "Grapes", "Vegetables"],
  },
  {
    id: "procin-super",
    name: "Procin Super",
    category: "Insecticides",
    composition: "Profenofos 40% + Cypermethrin 4% EC",
    dose: "2-2.5 ml/L",
    packingSizes: ["250 ml", "500 ml", "1 L", "5 L"],
    suitableCrops: ["Cotton", "Paddy", "Vegetables", "Pulses"],
  },
  {
    id: "neuroclam",
    name: "Neuroclam",
    category: "Insecticides",
    composition: "Emamectin Benzoate 5% WG",
    dose: "76-88g/acre",
    packingSizes: ["50 g", "100 g", "250 g", "500 g"],
    suitableCrops: ["Tea", "Grapes", "Cotton", "Okra", "Cabbage", "Cauliflower", "Chili"],
  },
  {
    id: "teromox",
    name: "Teromox",
    category: "Insecticides",
    composition: "Thiamethoxam 25% WG",
    dose: "40-80 grams/acre",
    packingSizes: ["50 g", "100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Cotton", "Rice", "Potatoes", "Tomatoes", "Brinjal", "Tea", "Fruits", "Vegetables"],
  },
  {
    id: "foxter",
    name: "Foxter",
    category: "Insecticides",
    composition: "Fipronil 40% + Imidacloprid 40% WG",
    dose: "50-200 g/acre",
    packingSizes: ["50 g", "100 g", "250 g", "500 g"],
    suitableCrops: ["Groundnut", "Vegetables", "Cotton"],
  },
  {
    id: "fiproshot",
    name: "Fiproshot",
    category: "Insecticides",
    composition: "Fipronil 0.6% GR",
    dose: "4 kg/acre",
    packingSizes: ["1 kg", "5 kg", "10 kg", "20 kg"],
    suitableCrops: ["Rice", "Sugarcane", "Wheat"],
  },
  {
    id: "lottery",
    name: "Lottery",
    category: "Insecticides",
    composition: "Chlorantraniliprole 0.4% w/w GR",
    dose: "4 kg/acre",
    packingSizes: ["1 kg", "5 kg", "10 kg", "20 kg"],
    suitableCrops: ["Paddy", "Sugarcane", "Groundnut"],
  },
  {
    id: "ragini",
    name: "Ragini",
    category: "Insecticides",
    composition: "Cartap Hydrochloride 50% SP",
    dose: "400 gm/acre",
    packingSizes: ["100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Paddy", "Brinjal", "Tomato", "Cabbage", "Cauliflower"],
  },
  {
    id: "dinar",
    name: "Dinar",
    category: "Insecticides",
    composition: "Cartap Hydrochloride 4% GR",
    dose: "7.5-10 kg/acre",
    packingSizes: ["1 kg", "5 kg", "10 kg", "20 kg"],
    suitableCrops: ["Rice", "Paddy"],
  },
  {
    id: "hepter",
    name: "Hepter",
    category: "Insecticides",
    composition: "Fenobucarb (BPMC) 50% EC",
    dose: "300-500 ml/acre",
    packingSizes: ["250 ml", "500 ml", "1 L", "5 L"],
    suitableCrops: ["Rice", "Mango", "Various crops"],
  },
  {
    id: "clotrin",
    name: "Clotrin",
    category: "Insecticides",
    composition: "Chlorantraniliprole 18.5% SC",
    dose: "150 ml/acre",
    packingSizes: ["50 ml", "100 ml", "250 ml", "500 ml"],
    suitableCrops: ["Sugarcane", "Vegetables"],
  },
  {
    id: "batsman",
    name: "Batsman",
    category: "Insecticides",
    composition: "Emamectin Benzoate 1.9% EC",
    dose: "75-150 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Cotton", "Chili", "Soybean", "Rice", "Broccoli", "Cauliflower", "Cabbage", "Okra", "Brinjal", "Tea", "Tomato"],
  },

  // Herbicides (3 products)
  {
    id: "clearzone",
    name: "Clearzone",
    category: "Herbicides",
    composition: "Paraquat Dichloride 24% SL",
    dose: "800-1000 ml/acre",
    packingSizes: ["250 ml", "500 ml", "1 L", "5 L"],
    suitableCrops: ["Tea", "Coffee", "Sugarcane", "Cotton", "Potato", "Rice", "Grapes"],
  },
  {
    id: "topramax",
    name: "Topramax",
    category: "Herbicides",
    composition: "Topramezone 336 g/l (w/v) SC",
    dose: "36 ml/acre",
    packingSizes: ["30 ml", "50 ml", "100 ml", "250 ml"],
    suitableCrops: ["Maize", "Corn"],
  },
  {
    id: "topmost",
    name: "Topmost",
    category: "Herbicides",
    composition: "Ammonium salt of glyphosate 71% SG",
    dose: "60-80 grams/15L",
    packingSizes: ["50 g", "100 g", "250 g", "500 g"],
    suitableCrops: ["Tea", "Plantation crops"],
  },

  // Fungicides (6 products)
  {
    id: "prepare",
    name: "Prepare",
    category: "Fungicides",
    composition: "Carbendazim 12% + Mancozeb 63% WP",
    dose: "300-500g/acre",
    packingSizes: ["100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Paddy", "Groundnut", "Potato", "Tea", "Grapes"],
  },
  {
    id: "adig",
    name: "Adig",
    category: "Fungicides",
    composition: "Azoxystrobin 18.2% + Difenoconazole 11.4% SC",
    dose: "200 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Paddy", "Chilli", "Tomato", "Maize", "Groundnut", "Soybean", "Tea", "Coffee"],
  },
  {
    id: "azitop",
    name: "Azitop",
    category: "Fungicides",
    composition: "Azoxystrobin 11% + Tebuconazole 18.3% SC",
    dose: "240-300 ml/acre",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Paddy", "Rice", "Chilli", "Grapes"],
  },
  {
    id: "silvet",
    name: "Silvet",
    category: "Fungicides",
    composition: "Silicone based Super Spreader Activator",
    dose: "40-50 ml/200L",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["All crops"],
  },
  {
    id: "tebuler",
    name: "Tebuler",
    category: "Fungicides",
    composition: "Tebuconazole 10% + Sulphur 65% WG",
    dose: "500 grams/acre",
    packingSizes: ["100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Chilli", "Soybean", "Groundnut", "Mango", "Apple", "Grapes", "Tomato", "Okra"],
  },
  {
    id: "saffer",
    name: "Saffer",
    category: "Fungicides",
    composition: "Sulphur 80% WDG",
    dose: "750-1000g/acre",
    packingSizes: ["250 g", "500 g", "1 kg", "5 kg"],
    suitableCrops: ["Grapes", "Mango", "Pea", "Apple", "Cumin", "Cowpea", "Guar", "Fruits", "Vegetables"],
  },

  // Plant Growth Regulators (4 products)
  {
    id: "kesar",
    name: "Kesar",
    category: "PGR",
    composition: "Gibberellic Acid 0.001% L",
    dose: "1 ml per 1L water",
    packingSizes: ["10 ml", "25 ml", "50 ml", "100 ml"],
    suitableCrops: ["Tomato", "Brinjal", "Okra", "Grapes", "Banana", "Cotton", "Paddy", "Wheat"],
  },
  {
    id: "alge",
    name: "Alge",
    category: "PGR",
    composition: "Gibberellic Acid 0.001% L",
    dose: "1 ml per 1L water",
    packingSizes: ["10 ml", "25 ml", "50 ml", "100 ml"],
    suitableCrops: ["Tomato", "Brinjal", "Okra", "Grapes", "Banana", "Cotton", "Paddy", "Wheat"],
  },
  {
    id: "enox",
    name: "Enox",
    category: "PGR",
    composition: "Alpha Napthyl Acetic acid 4.5% SL",
    dose: "0.25-0.5 ml/L",
    packingSizes: ["30 ml", "50 ml", "100 ml", "250 ml"],
    suitableCrops: ["Mango", "Grapes", "Pineapple", "Chili", "Tomato", "Cotton"],
  },
  {
    id: "revital-ultra",
    name: "Revital Ultra",
    category: "PGR",
    composition: "Organic plant growth promoter & bio stimulant",
    dose: "2-3 sprays",
    packingSizes: ["500 ml", "1 L", "5 L"],
    suitableCrops: ["Vegetables", "General plant growth"],
  },

  // Bio-Fertilizers (2 products)
  {
    id: "rootgrowth",
    name: "Rootgrowth",
    category: "Bio-Fertilizers",
    composition: "Lyophilized root growth bio-fertilizer",
    dose: "1-2 kg per acre",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["Fruits", "Vegetables", "Cereals", "Pulses"],
  },
  {
    id: "mykocin",
    name: "Mykocin",
    category: "Bio-Fertilizers",
    composition: "Mycorrhiza (Bio-Fertilizer)",
    dose: "Dip roots before planting",
    packingSizes: ["250 g", "500 g", "1 kg", "5 kg"],
    suitableCrops: ["Fruits", "Vegetables", "Cereals", "Pulses"],
  },

  // Fertilizers & Micronutrients (9 products)
  {
    id: "dost",
    name: "Dost",
    category: "Fertilizers",
    composition: "NPK 00:52:34",
    dose: "1.5-2 kg/acre",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["Grapes", "Pomegranate", "Banana", "Tomato", "Onion"],
  },
  {
    id: "sarthi",
    name: "Sarthi",
    category: "Fertilizers",
    composition: "NPK 00:00:50",
    dose: "1-1.5 kg/acre",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["Fruits", "Vegetables"],
  },
  {
    id: "poshan",
    name: "Poshan",
    category: "Fertilizers",
    composition: "NPK 19:19:19",
    dose: "2-5 grams/liter",
    packingSizes: ["100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Vegetables", "Fruits", "Flowers"],
  },
  {
    id: "super-food",
    name: "Super Food",
    category: "Fertilizers",
    composition: "Micronutrient Mixture (Zn, Fe, B, Mn, Cu, Mo)",
    dose: "4-5 grams near roots",
    packingSizes: ["250 g", "500 g", "1 kg", "5 kg"],
    suitableCrops: ["Fruits", "Vegetables", "Cereals", "Pulses"],
  },
  {
    id: "microman",
    name: "Microman",
    category: "Fertilizers",
    composition: "Zn 6%, Fe 3%, Mn 2%, Cu 1%, B 1%",
    dose: "1.5-2 kg/acre",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["Flowering", "Fruits", "Vegetables"],
  },
  {
    id: "magnet",
    name: "Magnet",
    category: "Fertilizers",
    composition: "Magnesium Sulphate (Epsom salt)",
    dose: "1-3 kg/acre in 200L water",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["All crops"],
  },
  {
    id: "ironman",
    name: "Ironman",
    category: "Fertilizers",
    composition: "Ferrous Sulphate 19% with Sulphur 10.5%",
    dose: "0-20 kg/acre",
    packingSizes: ["500 g", "1 kg", "5 kg", "10 kg"],
    suitableCrops: ["Fruits", "Vegetables", "Cereals", "Pulses"],
  },
  {
    id: "calceto",
    name: "Calceto",
    category: "Fertilizers",
    composition: "Calcium Chloride",
    dose: "0.2-0.3% concentration",
    packingSizes: ["100 g", "250 g", "500 g", "1 kg"],
    suitableCrops: ["Flowering", "Fruits", "Vegetables"],
  },
  {
    id: "max-more",
    name: "Max More",
    category: "Fertilizers",
    composition: "Micronutrient mixture",
    dose: "1-2 ml/liter",
    packingSizes: ["100 ml", "250 ml", "500 ml", "1 L"],
    suitableCrops: ["Paddy", "Fruits", "Vegetables"],
  },
];

export const categories = [
  { id: "insecticides", name: "Insecticides", count: 17 },
  { id: "herbicides", name: "Herbicides", count: 3 },
  { id: "fungicides", name: "Fungicides", count: 6 },
  { id: "pgr", name: "Plant Growth Regulators", count: 4 },
  { id: "bio-fertilizers", name: "Bio-Fertilizers", count: 2 },
  { id: "fertilizers", name: "Fertilizers & Micronutrients", count: 9 },
];

export const getProductsByCategory = (category: string) => {
  const categoryMap: { [key: string]: Product["category"] } = {
    insecticides: "Insecticides",
    herbicides: "Herbicides",
    fungicides: "Fungicides",
    pgr: "PGR",
    "bio-fertilizers": "Bio-Fertilizers",
    fertilizers: "Fertilizers",
  };

  return products.filter((product) => product.category === categoryMap[category]);
};
